spring:
  datasource:
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}   #  Email usado para enviar correos (tomado de variable de entorno)
    password: ${EMAIL_PASSWORD}   #  Contrase침a del email (debe ser una contrase침a de aplicaci칩n de Gmail) 
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    org.springframework.security: DEBUG  #  Nivel de log para depuraci칩n de seguridad
