spring:
  datasource:
    url: ${DB_URL}
    password: ${PASSWORD}
    username: ${USERNAME}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false