spring:
  datasource:
    url: ${DB_URL}            #  Variable de entorno con la URL de la base de datos
    username: ${DB_USERNAME}  #  Usuario de la base de datos (configurado en el sistema)
    password: ${DB_PASSWORD}  #  Contraseña de la base de datos (almacenada como variable de entorno)
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER:default@example.com}   #  Email usado para enviar correos (tomado de variable de entorno)
    password: ${EMAIL_PASSWORD:defaultpassword}   #  Contraseña del email (debe ser una contraseña de aplicación de Gmail) 
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    org.springframework.security: DEBUG  #  Nivel de log para depuración de seguridad
